[batch]
size = 6

[colors]
cap = "#1A1A1A"
prim = "white"
aux = "#F99963"
sys = "#C2E189"
mod = "#56B7E6"

[default]
family = "klp_lame"
variant = "choc_choc"
color = "$cap"
legend.1.size = 4
legend.1.color = "$prim"
legend.1.font = "FiraCode Nerd Font:style=Medium"
legend.2.size = 3
legend.2.color = "$aux"
legend.2.font = "FiraCode Nerd Font:style=Medium"
legend.3.size = 3
legend.3.color = "$sys"
legend.3.font = "FiraCode Nerd Font:style=Medium"

[rows.r0]
kind = "nt"
legends.1.text = ["[{", "!1", "@2", "#3", "$4", "%5", "^6", "&7", "*8", "(9", ")0", "]}"]

[rows.r1]
kind = "n"
legend.3.color = "$sys"

legends.1.text = ["󰌒", "Q", "W", "F", "P", "B", "J", "L", "U", "Y", ":;", "_-"]
legends.2.text = ["󰝝", "󰖨", "",  "",  "",  "",  "",  "",  "",  "",  "",   ""]
legends.3.text = ["", "",  "",  "",  "",  "󱐥", "",  "",  "",  "",  "",   ""]

[rows.r2]
kind = "n"

# Override T and N as 'normal homing' key kinds.
kinds.4 = "nh"
kinds.7 = "nh"
legends.1.text  = ["`~", "A", "R", "S", "T",  "G", "M", "N",  "E", "I", "O", "'\""]
legends.2.text  = ["󰝞",  "", "󰒮", "󰐎", "󰒭",  "",  "",  "󰁍",  "󰁅", "󰁝", "󰁔", ""]
legends.3.text  = ["󰜉",  "󰘴", "󰘵", "󰘳", "󰘶",  "", "",  "󰘶",  "󰘳", "󰘵", "󰘴", "󰜉"]
legends.3.color = ["",  "$mod", "$mod", "$mod", "$mod", "", "", "$mod",  "$mod", "$mod", "$mod", ""]

[rows.r3]
kind = "nt"
rotate = 180

legends.1.text  = ["\\|",  "Z", "X", "C", "D", "V", "K",  "H",  ",<", ".>", "/?", "+="]
legends.2.text  = ["󰝟",    "󰍽", "",  "󰓛", "",  "",  "",   "",   "",   "",   "",   ""]
legends.3.text  = ["",    "",  "",  "",  "",  "", "󰂱¹", "󰂱²", "󰂱³", "󰂱⁴", "󰂱⁵", "󰂲"]
legends.3.color = ["$mod", "",  "",  "",  "",  "",  "",   "",   "",   "",   "",   ""]

[rows.r4]
kind = "st"

legends.1.color.3 = "$mod"
legends.1.color.4 = "$mod"
legends.1.text    = ["",  "",  "󰭜", "HYP", "HYP", "󱁐", "",  ""]
legends.2.text    = ["", "󰃕", "󱣱", "",    "",    "󰎠", "󰃕", ""]

[rows.thumbs]
kind = "s1.5v"
rotate = 90

legends.1.text = ["⎋", "󰌑"]
legends.2.text = ["󰘦", ""]
