[batch]
size = 6

[colors]
cap = "#1A1A1A"
prim = "white"
aux = "#F99963"
sys = "#C2E189"
mod = "#56B7E6"

[default]
family = "klp_lame"
variant = "choc_choc"
font = "FiraCode Nerd Font:style=Medium"
color = "$cap"
primary.size = 4
primary.color = "$prim"
secondary.size = 3
secondary.color = "$aux"
tertiary.size = 3
tertiary.color = "$sys"

[rows.r0]
kind = "nt"
primaries.legend = ["[{", "!1", "@2", "#3", "$4", "%5", "^6", "&7", "*8", "(9", ")0", "]}"]

[rows.r1]
kind = "n"
tertiary.color   = "$sys"

primaries.legend   = ["󰌒", "Q", "W", "F", "P", "B", "J", "L", "U", "Y", ":;", "_-"]
secondaries.legend = ["󰝝", "󰖨", "",  "",  "",  "",  "",  "",  "",  "",  "",   ""]
tertiaries.legend  = ["", "",  "",  "",  "",  "󱐥", "",  "",  "",  "",  "",   ""]

[rows.r2]
kind = "n"

# Override T and N as 'normal homing' key kinds.
kinds.4 = "nh"
kinds.7 = "nh"
primaries.legend   = ["`~", "A", "R", "S", "T",  "G", "M", "N",  "E", "I", "O", "'\""]
secondaries.legend = ["󰝞",  "", "󰒮", "󰐎", "󰒭",  "",  "",  "󰁍",  "󰁅", "󰁝", "󰁔", ""]
tertiaries.legend  = ["󰜉",  "󰘴", "󰘵", "󰘳", "󰘶",  "", "",  "󰘶",  "󰘳", "󰘵", "󰘴", "󰜉"]
tertiaries.color   = ["",  "$mod", "$mod", "$mod", "$mod", "", "", "$mod",  "$mod", "$mod", "$mod", ""]

[rows.r3]
kind = "nt"
rotate = 180

primaries.legend   = ["\\|",  "Z", "X", "C", "D", "V", "K",  "H",  ",<", ".>", "/?", "+="]
secondaries.legend = ["󰝟",    "󰍽", "",  "󰓛", "",  "",  "",   "",   "",   "",   "",   ""]
tertiaries.legend  = ["",    "",  "",  "",  "",  "", "󰂱¹", "󰂱²", "󰂱³", "󰂱⁴", "󰂱⁵", "󰂲"]
tertiaries.color   = ["$mod", "",  "",  "",  "",  "",  "",   "",   "",   "",   "",   ""]

[rows.r4]
kind = "st"

primaries.color.3 = "$mod"
primaries.color.4 = "$mod"
primaries.legend   = ["",  "",  "󰭜", "HYP", "HYP", "󱁐", "",  ""]
secondaries.legend = ["", "󰃕", "󱣱", "",    "",    "󰎠", "󰃕", ""]

[rows.thumbs]
kind = "s1.5v"
rotate = 90

primaries.legend   = ["⎋", "󰌑"]
secondaries.legend = ["󰘦", ""]
